#数据库配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ssm_db?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: root

#配置Mp相关配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#端口配置
server:
  port: 8080

